// Maps moduleSlug to what the Generate button should say
// e.g., "Generate PRD" not "Generate PRD Generator"
const outputNames: Record<string, string> = {
  'prd': 'PRD',
  'user-stories': 'User Stories',
  'brief': 'Product Brief',
  'one-pager': 'One-Pager',
  'tech-spec': 'Technical Spec',
  'api-docs': 'API Documentation',
  'onboarding': 'Onboarding Flow',
  'interviews': 'Interview Analysis',
  'synthesis': 'Research Synthesis',
  'personas': 'Persona Profile',
  'jtbd': 'JTBD Analysis',
  'feedback': 'Feedback Analysis',
  'surveys': 'Survey Questions',
  'app-reviews': 'Review Analysis',
  'feature-requests': 'Feature Request Analysis',
  'customer-voice': 'VoC Report',
  'positioning': 'Positioning Statement',
  'gtm': 'GTM Strategy',
  'okrs': 'OKR Set',
  'north-star': 'North Star Definition',
  'vpc': 'Value Proposition',
  'build-vs-buy': 'Build vs Buy Analysis',
  'ai-strategy': 'AI Strategy',
  'pricing': 'Pricing Analysis',
  'roadmap-review': 'Roadmap Review',
  'devils-advocate': 'Contrarian Analysis',
  'roadmap': 'Roadmap',
  'quarterly': 'Quarterly Plan',
  'sprints': 'Sprint Plan',
  'decomposition': 'Feature Breakdown',
  'daily': 'Daily Plan',
  'weekly': 'Weekly Plan',
  'metrics': 'Metric Framework',
  'ab-design': 'A/B Test Design',
  'ab-analysis': 'A/B Test Analysis',
  'funnels': 'Funnel Analysis',
  'experiments': 'Experiment Design',
  'dashboards': 'Dashboard Spec',
  'profiles': 'Competitor Profile',
  'market-sizing': 'Market Sizing',
  'win-loss': 'Win/Loss Analysis',
  'release-notes': 'Release Notes',
  'exec-update': 'Executive Update',
  'stakeholder-sim': 'Stakeholder Analysis',
  'meeting-notes': 'Meeting Notes',
  'decision-doc': 'Decision Document',
  'board-deck': 'Board Deck Outline',
  'agenda': 'Meeting Agenda',
  'announcement': 'Announcement',
  'checklist': 'Launch Checklist',
  'sales-enablement': 'Sales Kit',
  'readiness': 'Readiness Assessment',
  'retro': 'Retrospective',
  'processes': 'Process Document',
  'post-mortem': 'Post-Mortem Report',
  'cs-playbook': 'CS Playbook',
  'meeting-templates': 'Meeting Template',
};

export function getOutputName(moduleSlug: string, moduleName: string): string {
  return outputNames[moduleSlug] || moduleName;
}
