export interface KBItem {
  id: string;
  title: string;
  category: 'framework' | 'mental-model' | 'book-summary';
  content: string;
  source?: string;
  tags: string[];
}

export const knowledgeBaseData: KBItem[] = [
  // ============ FRAMEWORKS ============
  {
    id: 'fw-rice',
    title: 'RICE Scoring',
    category: 'framework',
    content: `**RICE** is a prioritization framework that scores features by four factors:\n\n- **Reach**: How many users will this impact in a given time period?\n- **Impact**: How much will this impact each user? (3 = massive, 2 = high, 1 = medium, 0.5 = low, 0.25 = minimal)\n- **Confidence**: How confident are you in your estimates? (100% = high, 80% = medium, 50% = low)\n- **Effort**: How many person-months will this take?\n\n**Formula**: RICE Score = (Reach × Impact × Confidence) / Effort\n\n**When to use**: Comparing features with different scopes, audiences, and effort levels. Best for product teams that need a quantitative, defensible way to prioritize.`,
    source: 'Intercom',
    tags: ['prioritization', 'scoring', 'product'],
  },
  {
    id: 'fw-jtbd',
    title: 'Jobs to be Done (JTBD)',
    category: 'framework',
    content: `**Jobs to be Done** focuses on the "job" a customer is trying to accomplish, not the product features.\n\n**Core Statement**: "When [situation], I want to [motivation], so I can [expected outcome]."\n\n**Key Concepts**:\n- Functional jobs: The practical task the customer wants to accomplish\n- Emotional jobs: How the customer wants to feel\n- Social jobs: How the customer wants to be perceived\n- Hiring/firing: Customers "hire" products to do jobs and "fire" them when they fail\n\n**When to use**: Discovery research, positioning, understanding why customers switch products. Helps avoid building features nobody needs by focusing on underlying motivations.`,
    source: 'Clayton Christensen',
    tags: ['discovery', 'research', 'strategy'],
  },
  {
    id: 'fw-aarrr',
    title: 'AARRR (Pirate Metrics)',
    category: 'framework',
    content: `**AARRR** (Pirate Metrics) breaks the customer lifecycle into 5 measurable stages:\n\n1. **Acquisition**: How do users find you? (channels, CAC, traffic)\n2. **Activation**: Do users have a great first experience? (signup completion, aha moment)\n3. **Retention**: Do users come back? (DAU/MAU, cohort retention, churn)\n4. **Revenue**: How do you monetize? (ARPU, LTV, conversion to paid)\n5. **Referral**: Do users tell others? (NPS, viral coefficient, referral rate)\n\n**When to use**: Building your analytics dashboard, identifying which stage of the funnel needs the most attention, aligning team on what metrics matter.`,
    source: 'Dave McClure, 500 Startups',
    tags: ['analytics', 'metrics', 'growth'],
  },
  {
    id: 'fw-scqa',
    title: 'SCQA (Situation-Complication-Question-Answer)',
    category: 'framework',
    content: `**SCQA** is a communication framework for structuring persuasive narratives:\n\n- **Situation**: What is the current state? (context the audience already knows)\n- **Complication**: What has changed? What's the challenge or opportunity?\n- **Question**: What question does this raise? (bridges to your recommendation)\n- **Answer**: What is your recommendation and supporting evidence?\n\n**When to use**: Executive updates, stakeholder presentations, product proposals, decision documents. Forces clarity and makes your ask impossible to miss.`,
    source: 'Barbara Minto, The Pyramid Principle',
    tags: ['communication', 'writing', 'leadership'],
  },
  {
    id: 'fw-okr',
    title: 'OKRs (Objectives & Key Results)',
    category: 'framework',
    content: `**OKRs** align teams around outcomes, not output:\n\n- **Objective**: Qualitative, inspiring, time-bound. What do you want to achieve?\n- **Key Results**: 3-5 quantitative measures. How will you know you achieved it?\n\n**Rules**:\n- Objectives should be ambitious (70% achievement = success)\n- Key Results must be measurable (not tasks or activities)\n- Set quarterly + annual OKRs\n- Grade transparently at end of period\n- OKRs cascade from company → team → individual\n\n**Common mistakes**: Making KRs binary (yes/no), setting too many OKRs, confusing KRs with tasks, not reviewing regularly.`,
    source: 'John Doerr, Measure What Matters',
    tags: ['strategy', 'goals', 'alignment'],
  },
  {
    id: 'fw-north-star',
    title: 'North Star Metric',
    category: 'framework',
    content: `The **North Star Metric** is a single metric that best captures the core value your product delivers to customers.\n\n**Characteristics of a good NSM**:\n- Reflects customer value (not just revenue)\n- Is a leading indicator of business success\n- Is measurable and actionable\n- Teams can influence it directly\n\n**Input Metrics**: 3-5 metrics that directly drive the NSM. These are what teams optimize day-to-day.\n\n**Examples**:\n- Spotify: Time spent listening\n- Airbnb: Nights booked\n- Slack: Messages sent in channels\n- Facebook: Daily active users\n\n**When to use**: Aligning the entire product team around a single measure of success. Prevents metric proliferation and conflicting priorities.`,
    source: 'Amplitude / Sean Ellis',
    tags: ['strategy', 'metrics', 'alignment'],
  },
  {
    id: 'fw-positioning',
    title: 'Obviously Awesome Positioning (April Dunford)',
    category: 'framework',
    content: `**April Dunford's Positioning Framework** has 5 components:\n\n1. **Competitive Alternatives**: What would customers use if you didn't exist?\n2. **Unique Attributes**: What features/capabilities do you have that alternatives don't?\n3. **Value**: What value do those unique attributes enable?\n4. **Target Customers**: Who cares most about that value?\n5. **Market Category**: What market frame makes your value obvious?\n\n**Process**: Work through these in order (not reverse). Start with competitive alternatives, not your target customer.\n\n**When to use**: Launching a new product, entering a new market, when sales conversations aren't landing, or when prospects keep comparing you to the wrong competitors.`,
    source: 'April Dunford, Obviously Awesome',
    tags: ['strategy', 'positioning', 'marketing'],
  },
  {
    id: 'fw-ost',
    title: 'Opportunity Solution Tree (Teresa Torres)',
    category: 'framework',
    content: `The **Opportunity Solution Tree** is a visual framework for continuous discovery:\n\n**Structure** (top to bottom):\n1. **Desired Outcome**: The business/product outcome you're trying to drive\n2. **Opportunities**: Customer needs, pain points, and desires (from research)\n3. **Solutions**: Possible ways to address each opportunity\n4. **Experiments**: Tests to validate each solution before building\n\n**Key Principles**:\n- Compare and contrast opportunities before jumping to solutions\n- Generate multiple solutions per opportunity\n- Test assumptions, don't just build\n- The tree is a living document, updated continuously\n\n**When to use**: Connecting business goals to customer research to actual product work. Prevents the team from jumping to solutions without understanding the problem space.`,
    source: 'Teresa Torres, Continuous Discovery Habits',
    tags: ['discovery', 'strategy', 'research'],
  },
  {
    id: 'fw-dhm',
    title: 'DHM Model (Gibson Biddle)',
    category: 'framework',
    content: `The **DHM Model** evaluates product strategy through three lenses:\n\n- **D - Delight**: Does this delight customers in hard-to-copy, margin-enhancing ways?\n- **H - Hard-to-copy**: What makes this difficult for competitors to replicate? (technology, network effects, brand, data, economies of scale)\n- **M - Margin-enhancing**: Does this improve margins through higher prices, lower costs, or increased engagement?\n\n**When to use**: Evaluating strategic product investments. A feature that delights but is easy to copy won't create lasting advantage. All three must align for a winning strategy.`,
    source: 'Gibson Biddle (former Netflix VP Product)',
    tags: ['strategy', 'competitive', 'product'],
  },
  {
    id: 'fw-ice',
    title: 'ICE Scoring',
    category: 'framework',
    content: `**ICE** is a simpler alternative to RICE for prioritization:\n\n- **Impact**: How much will this move the needle? (1-10)\n- **Confidence**: How sure are you about the impact? (1-10)\n- **Ease**: How easy is this to implement? (1-10)\n\n**Formula**: ICE Score = Impact × Confidence × Ease\n\n**When to use**: Quick prioritization when you don't have detailed reach/effort data. Good for growth experiments and rapid iteration. Less rigorous than RICE but faster to apply.`,
    source: 'Sean Ellis, GrowthHackers',
    tags: ['prioritization', 'scoring', 'growth'],
  },
  {
    id: 'fw-moscow',
    title: 'MoSCoW Prioritization',
    category: 'framework',
    content: `**MoSCoW** categorizes requirements into four buckets:\n\n- **Must Have**: Non-negotiable. The product fails without these.\n- **Should Have**: Important but not critical. Can work around temporarily.\n- **Could Have**: Nice to have. Include if time/resources allow.\n- **Won't Have (this time)**: Explicitly out of scope. Parking lot for future.\n\n**When to use**: Sprint planning, release scoping, stakeholder alignment on what's in/out. Forces explicit prioritization conversations and prevents scope creep.`,
    source: 'Dai Clegg, Oracle',
    tags: ['prioritization', 'planning', 'requirements'],
  },
  {
    id: 'fw-kano',
    title: 'Kano Model',
    category: 'framework',
    content: `The **Kano Model** classifies features by how they affect satisfaction:\n\n- **Must-Be (Basic)**: Expected. Absence causes dissatisfaction, presence doesn't delight. (e.g., login works)\n- **Performance (Linear)**: More is better. Directly proportional to satisfaction. (e.g., speed, storage)\n- **Attractive (Delighters)**: Unexpected. Absence is fine, but presence creates disproportionate delight. (e.g., AI autocomplete)\n- **Indifferent**: Users don't care either way.\n- **Reverse**: Some users actively dislike it.\n\n**Key insight**: Over time, Delighters become Performance features, and Performance features become Must-Be. You must keep innovating.\n\n**When to use**: Deciding what to build next. Invest in Must-Be to avoid churn, Performance for competitive advantage, Attractive for differentiation.`,
    source: 'Noriaki Kano',
    tags: ['prioritization', 'product', 'customer'],
  },
  {
    id: 'fw-tam-sam-som',
    title: 'TAM SAM SOM (Market Sizing)',
    category: 'framework',
    content: `**TAM/SAM/SOM** sizes your market opportunity:\n\n- **TAM (Total Addressable Market)**: Total revenue if you had 100% market share globally\n- **SAM (Serviceable Addressable Market)**: Portion of TAM you can realistically target (geography, segment, use case)\n- **SOM (Serviceable Obtainable Market)**: Realistic market share you can capture in 3-5 years\n\n**Two approaches**:\n- **Top-down**: Start with industry reports, narrow down\n- **Bottom-up**: Start with your unit economics and scale up (usually more credible)\n\n**When to use**: Business cases, investor pitches, evaluating new markets, strategic planning.`,
    source: 'Standard business strategy',
    tags: ['strategy', 'market', 'competitive'],
  },
  {
    id: 'fw-vale-prop-canvas',
    title: 'Value Proposition Canvas',
    category: 'framework',
    content: `The **Value Proposition Canvas** maps customer needs to your offering:\n\n**Customer Profile (right side)**:\n- Customer Jobs: What are they trying to accomplish?\n- Pains: What annoys them, what risks do they face?\n- Gains: What outcomes do they want?\n\n**Value Map (left side)**:\n- Products & Services: What do you offer?\n- Pain Relievers: How do you address their pains?\n- Gain Creators: How do you create their desired gains?\n\n**Fit** occurs when your Pain Relievers and Gain Creators align with the most important Customer Pains and Gains.\n\n**When to use**: Product-market fit analysis, positioning workshops, evaluating new feature ideas.`,
    source: 'Alexander Osterwalder, Strategyzer',
    tags: ['strategy', 'product', 'customer'],
  },

  // ============ MENTAL MODELS ============
  {
    id: 'mm-first-principles',
    title: 'First Principles Thinking',
    category: 'mental-model',
    content: `**First Principles Thinking** breaks problems down to their fundamental truths and reasons up from there.\n\n**Process**:\n1. Identify your assumptions about the problem\n2. Break down the problem to its most basic elements\n3. Build up from the fundamentals\n\n**Example**: Instead of "shipping is expensive, so we can't offer free shipping," think: What actually makes up shipping cost? (weight, distance, volume, packaging). Can we reduce any of these? Can we change the model entirely?\n\n**PM Application**: When stakeholders say "we've always done it this way" or "that's how the industry works," challenge the underlying assumptions. Don't reason by analogy — reason from fundamentals.`,
    tags: ['thinking', 'strategy', 'problem-solving'],
  },
  {
    id: 'mm-inversion',
    title: 'Inversion',
    category: 'mental-model',
    content: `**Inversion** means thinking about problems backwards: instead of asking "how do I succeed?" ask "how would I guarantee failure?"\n\n**Process**:\n1. Define the goal\n2. List everything that would cause failure\n3. Systematically avoid those things\n\n**PM Examples**:\n- "How do we make this launch fail?" → Don't train support, don't have a rollback plan, don't communicate to stakeholders\n- "How do we guarantee users won't adopt?" → Make onboarding confusing, hide the value, require too many steps\n\n**Why it works**: It's often easier to identify what NOT to do than what to do. Avoiding stupidity is more reliable than seeking brilliance.`,
    tags: ['thinking', 'strategy', 'problem-solving'],
  },
  {
    id: 'mm-second-order',
    title: 'Second-Order Thinking',
    category: 'mental-model',
    content: `**Second-Order Thinking** considers the consequences of consequences.\n\n**First-order**: What happens immediately?\n**Second-order**: What happens as a result of the first thing happening?\n**Third-order**: What happens because of the second thing?\n\n**PM Examples**:\n- First-order: Add a pricing page discount → More signups\n- Second-order: Users anchor on the discounted price → Harder to upsell later\n- Third-order: Team optimizes for discount conversions → Brand perception shifts to "cheap"\n\n**When to use**: Before any significant product decision. Ask "and then what?" at least twice. Most product mistakes come from optimizing for first-order effects while ignoring second-order consequences.`,
    tags: ['thinking', 'strategy', 'decision-making'],
  },
  {
    id: 'mm-circle-competence',
    title: 'Circle of Competence',
    category: 'mental-model',
    content: `**Circle of Competence**: Know what you know, know what you don't know, and stay honest about the boundary.\n\n**Three zones**:\n1. **Inside**: Deep expertise. You can make high-quality decisions quickly.\n2. **Edge**: Some knowledge. You need more research or expert input.\n3. **Outside**: No expertise. Defer to others or invest time learning.\n\n**PM Application**: A PM doesn't need to be the expert in everything — they need to know who IS the expert. When you're outside your circle (infra decisions, legal implications, pricing models), admit it and bring in the right people. The biggest PM mistakes come from overconfidence outside the circle.`,
    tags: ['thinking', 'leadership', 'self-awareness'],
  },
  {
    id: 'mm-map-territory',
    title: 'The Map is Not the Territory',
    category: 'mental-model',
    content: `**The Map is Not the Territory**: Models, dashboards, and metrics are simplifications of reality — don't confuse them for reality itself.\n\n**PM Application**:\n- Your personas are useful models, but real users are more nuanced\n- Your analytics dashboard shows what happened, not why\n- Your roadmap is a plan, not a commitment\n- Your A/B test results apply to the tested population, not all users\n\n**Key insight**: Use models as starting points, not endpoints. Always seek direct contact with reality (talk to users, observe behavior, test assumptions). When the map and territory disagree, trust the territory.`,
    tags: ['thinking', 'research', 'analytics'],
  },
  {
    id: 'mm-leverage',
    title: 'Leverage Points',
    category: 'mental-model',
    content: `**Leverage Points**: Find the places in a system where a small change produces outsized results.\n\n**High-leverage PM actions**:\n- Fixing onboarding (affects every new user)\n- Reducing the #1 support ticket reason (saves time for every team)\n- Improving the activation metric (compounds over time)\n- Automating a manual process (frees up future capacity)\n\n**Low-leverage PM traps**:\n- Optimizing a feature 0.1% of users touch\n- Adding features instead of fixing existing ones\n- Spending weeks on pixel-perfect specs for uncertain features\n\n**Rule**: Before working on anything, ask "what's the leverage?" If you can't articulate why this specific thing will move the needle, reconsider.`,
    tags: ['thinking', 'strategy', 'prioritization'],
  },
  {
    id: 'mm-reversible',
    title: 'One-Way vs Two-Way Doors',
    category: 'mental-model',
    content: `**One-Way Doors (Type 1)**: Irreversible decisions. High stakes. Take your time.\n**Two-Way Doors (Type 2)**: Reversible decisions. Low stakes. Move fast.\n\n**PM Application**:\n- **Type 1** (deliberate): Pricing model changes, platform migrations, public API contracts, removing features, org restructuring\n- **Type 2** (move fast): UI copy, feature flags, experiment variants, internal tools, onboarding flow tweaks\n\n**The mistake**: Treating Type 2 decisions like Type 1 (analysis paralysis on reversible things) or treating Type 1 decisions like Type 2 (rushing irreversible commitments).\n\n**Rule**: Default to speed. Only slow down for truly one-way doors.`,
    source: 'Jeff Bezos, Amazon',
    tags: ['decision-making', 'strategy', 'leadership'],
  },
  {
    id: 'mm-pareto',
    title: 'Pareto Principle (80/20)',
    category: 'mental-model',
    content: `**The Pareto Principle**: Roughly 80% of effects come from 20% of causes.\n\n**PM Applications**:\n- 80% of user value comes from 20% of features → Focus on those features\n- 80% of bugs come from 20% of the codebase → Fix that codebase\n- 80% of support tickets come from 20% of issues → Solve those issues\n- 80% of revenue comes from 20% of customers → Understand those customers\n\n**Action**: Before any large initiative, identify the 20% that drives 80% of the outcome. Build for that first. "What's the 20% effort version of this feature that delivers 80% of the value?"`,
    tags: ['prioritization', 'thinking', 'strategy'],
  },
  {
    id: 'mm-opportunity-cost',
    title: 'Opportunity Cost',
    category: 'mental-model',
    content: `**Opportunity Cost**: The value of what you give up by choosing one option over another.\n\n**PM Application**: Every feature you build is a feature you DON'T build. Every meeting you attend is time you DON'T spend with customers. Every fire you fight is a strategy decision you DON'T make.\n\n**Questions to ask**:\n- "What's the best alternative use of this engineering time?"\n- "If we build Feature A, what won't we be able to build this quarter?"\n- "Is attending this meeting worth more than the work I'd otherwise do?"\n\n**The hidden cost**: The biggest opportunity cost in product is usually NOT the features you choose — it's the time spent on features nobody wanted.`,
    tags: ['decision-making', 'prioritization', 'strategy'],
  },
  {
    id: 'mm-confirmation-bias',
    title: 'Confirmation Bias',
    category: 'mental-model',
    content: `**Confirmation Bias**: We seek information that confirms our existing beliefs and ignore information that contradicts them.\n\n**PM Danger Zones**:\n- Interpreting user research to confirm your solution idea\n- Cherry-picking metrics that support your feature\n- Only talking to users who love your product\n- Ignoring churn data while celebrating growth\n\n**Countermeasures**:\n- Actively seek disconfirming evidence\n- Ask "what would make me change my mind?"\n- Have a devil's advocate in product reviews\n- Pre-register your experiment hypotheses\n- Read negative reviews and churned-user feedback first`,
    tags: ['thinking', 'research', 'decision-making'],
  },

  // ============ BOOK SUMMARIES ============
  {
    id: 'bs-inspired',
    title: 'Inspired (Marty Cagan)',
    category: 'book-summary',
    content: `**Core thesis**: The best product teams discover and deliver solutions that are valuable (customers want it), usable (they can use it), feasible (engineers can build it), and viable (the business can support it).\n\n**Key takeaways**:\n- **Product discovery** is the most important PM activity — validated learning before committing to build\n- **Empowered teams** vs feature teams: give teams problems to solve, not features to build\n- **Prototype before you build**: Use rapid prototyping to test value and usability\n- **Missionary vs mercenary teams**: Missionaries believe in the vision; mercenaries just ship tickets\n- **Product vision** should inspire; **product strategy** should focus; **product discovery** should de-risk\n\n**Who should read**: Every PM, especially those in orgs that treat product as a service org for stakeholders.`,
    source: 'Marty Cagan',
    tags: ['product', 'discovery', 'leadership'],
  },
  {
    id: 'bs-empowered',
    title: 'Empowered (Marty Cagan)',
    category: 'book-summary',
    content: `**Core thesis**: Ordinary product teams just build what they're told. Extraordinary product teams are given problems to solve and empowered to find the best solutions.\n\n**Key takeaways**:\n- **Product leadership** is about coaching, not directing\n- **Product strategy** = focus. Decide what problems matter most and say no to everything else\n- **Team topology**: PM + Designer + Tech Lead = the minimum empowered team\n- **Stakeholder management**: Transform stakeholders from roadmap dictators into collaborative partners\n- **Product culture**: Move from output-focused (features shipped) to outcome-focused (problems solved)\n\n**Who should read**: Product leaders, engineering managers, and anyone frustrated by a "feature factory" culture.`,
    source: 'Marty Cagan',
    tags: ['leadership', 'product', 'culture'],
  },
  {
    id: 'bs-obviously-awesome',
    title: 'Obviously Awesome (April Dunford)',
    category: 'book-summary',
    content: `**Core thesis**: Most products fail not because they're bad, but because customers don't understand what they are and why they should care. Positioning fixes this.\n\n**Key takeaways**:\n- Positioning is NOT messaging. It's the strategic context that makes your value obvious.\n- Start with competitive alternatives (not your target customer)\n- Your unique attributes only matter if they translate to customer value\n- Choose a market category that helps (not hurts) your positioning\n- The "best customer" is whoever gets the most value from your unique attributes\n\n**The 5-step process**: Competitive alternatives → Unique attributes → Value → Best customers → Market category\n\n**Who should read**: Any PM whose product is misunderstood, compared to wrong competitors, or struggling with conversion.`,
    source: 'April Dunford',
    tags: ['positioning', 'strategy', 'marketing'],
  },
  {
    id: 'bs-measure-what-matters',
    title: 'Measure What Matters (John Doerr)',
    category: 'book-summary',
    content: `**Core thesis**: OKRs (Objectives and Key Results) drive focus, alignment, tracking, and stretching in organizations of any size.\n\n**Key takeaways**:\n- **Objectives** are qualitative and inspiring; **Key Results** are quantitative and measurable\n- Aim for 70% achievement on stretch OKRs (100% = set the bar too low)\n- OKRs should be transparent across the whole org\n- **CFRs** (Conversations, Feedback, Recognition) complement OKRs with continuous performance management\n- Start with company-level OKRs, then cascade to teams (but allow bottom-up input)\n\n**Common pitfalls**: Too many OKRs, KRs that are really tasks, not reviewing regularly, using OKRs for performance evaluation.\n\n**Who should read**: Anyone implementing or improving goal-setting at their company.`,
    source: 'John Doerr',
    tags: ['goals', 'strategy', 'alignment'],
  },
  {
    id: 'bs-continuous-discovery',
    title: 'Continuous Discovery Habits (Teresa Torres)',
    category: 'book-summary',
    content: `**Core thesis**: Product teams need a structured, sustainable approach to customer discovery that happens every week — not just during "research phases."\n\n**Key takeaways**:\n- **Weekly customer touchpoints**: Talk to at least one customer every week\n- **Opportunity Solution Trees**: Map outcomes → opportunities → solutions → experiments\n- **Interview snapshots**: Capture key moments from customer stories\n- **Assumption testing**: Identify the riskiest assumptions and test them before building\n- **Compare and contrast**: Always consider multiple solutions and multiple opportunities\n\n**The habit**: Discovery isn't a phase — it's a continuous practice woven into weekly work.\n\n**Who should read**: PMs who want to build a sustainable research practice, not just sporadic user interviews.`,
    source: 'Teresa Torres',
    tags: ['discovery', 'research', 'habits'],
  },
  {
    id: 'bs-build-trap',
    title: 'Escaping the Build Trap (Melissa Perri)',
    category: 'book-summary',
    content: `**Core thesis**: Companies fall into the "build trap" when they measure success by output (features shipped) instead of outcomes (value delivered).\n\n**Key takeaways**:\n- **The build trap**: Shipping features that don't solve real problems\n- **Product-led organizations**: Align around customer and business outcomes\n- **Strategy deployment**: Company vision → Strategic intents → Product initiatives → Options\n- **Product kata**: Understand direction → Understand current state → Set next target → Choose step → Run experiments\n- **Kill bad ideas early**: Most ideas won't work. That's fine. Discover this before investing in full builds.\n\n**Who should read**: PMs in orgs where the roadmap is a list of stakeholder requests, and "done" means "shipped" not "solved."`,
    source: 'Melissa Perri',
    tags: ['product', 'strategy', 'culture'],
  },
  {
    id: 'bs-lean-startup',
    title: 'The Lean Startup (Eric Ries)',
    category: 'book-summary',
    content: `**Core thesis**: Startups should use scientific experimentation to test business hypotheses as quickly and cheaply as possible.\n\n**Key takeaways**:\n- **Build-Measure-Learn loop**: Build an MVP, measure real behavior, learn from results\n- **MVP (Minimum Viable Product)**: The smallest thing you can build to test your riskiest assumption\n- **Validated learning**: Every experiment should teach you something useful\n- **Pivot or persevere**: Based on data, decide whether to change direction or double down\n- **Innovation accounting**: New metrics for uncertain environments (not just revenue/growth)\n\n**When to apply**: Launching new products, entering new markets, testing bold hypotheses. Less relevant for mature products optimizing incrementally.\n\n**Who should read**: First-time PMs, startup founders, anyone building something with high uncertainty.`,
    source: 'Eric Ries',
    tags: ['product', 'strategy', 'experimentation'],
  },
  {
    id: 'bs-thinking-fast-slow',
    title: 'Thinking, Fast and Slow (Daniel Kahneman)',
    category: 'book-summary',
    content: `**Core thesis**: Humans have two thinking systems — fast intuition (System 1) and slow deliberation (System 2) — and we're predictably irrational.\n\n**Key PM-relevant insights**:\n- **Anchoring**: First numbers shown heavily influence estimates (pricing, effort estimates)\n- **Loss aversion**: Users feel losses ~2x more than equivalent gains (be careful removing features)\n- **Availability heuristic**: We overweight recent/vivid events (the loud customer isn't representative)\n- **Planning fallacy**: We systematically underestimate time/effort (add buffers to roadmaps)\n- **Framing effects**: How you present information changes decisions (A/B test your messaging)\n\n**Who should read**: Every PM. Understanding cognitive biases makes you better at research, decision-making, and designing user experiences.`,
    source: 'Daniel Kahneman',
    tags: ['thinking', 'psychology', 'decision-making'],
  },
  {
    id: 'bs-high-output',
    title: 'High Output Management (Andy Grove)',
    category: 'book-summary',
    content: `**Core thesis**: A manager's output = the output of their team + the output of adjacent teams they influence.\n\n**Key PM-relevant insights**:\n- **Leverage**: Focus on high-leverage activities that multiply your impact\n- **Meetings as work**: Meetings are a legitimate tool, not a waste. 1:1s and decision meetings are highest value.\n- **Decision-making**: Gather input from the lowest level, make decisions at the right level, communicate broadly\n- **Dual reporting**: Product teams report to both functional (PM, Eng, Design) and project (the product itself) hierarchies\n- **Indicators**: Choose a small set of leading indicators and review them regularly\n\n**Who should read**: PMs transitioning to leadership roles, or any PM who wants to think about their work as a system rather than a task list.`,
    source: 'Andy Grove, Intel',
    tags: ['leadership', 'management', 'productivity'],
  },
];
